// Netlify Function (v2, ESM) — same-origin rating API, exposed directly at
// /api/rating via `config.path` below (no manual _redirects edit needed —
// that file is machine-generated by build/generate-landing.js from the SEO
// registry and would be silently overwritten on the next `npm run generate`
// if a rating route were hand-added there instead).
//
// Storage: Netlify Blobs (`@netlify/blobs`) — the smallest persistence
// layer that reuses the project's existing Netlify deploy with zero new
// vendor/credentials. `getStore()` auto-authenticates using the deploy's
// own context in production and under `netlify dev` locally; nothing to
// configure. `consistency:"strong"` trades a little latency for
// read-after-write correctness. This is a real key/value store, not a
// relational DB — see readModifyWrite() below for the honest limit of the
// concurrency guarantee it gives us.
//
// Tool identity: TOOL_IDS is copied from seo/tools-registry.json +
// seo/additional-tools.json's own toolId fields (the same canonical ids
// js/core/nav-menu.js's CATEGORIES already uses) rather than trusting
// whatever id a client sends — a request naming an id outside this list is
// rejected before it ever reaches storage.
import { getStore } from "@netlify/blobs";
import crypto from "node:crypto";

export const config = { path: "/api/rating" };

// Kept as a plain literal (not read from the JSON registry at request time)
// so this function has no filesystem dependency on the SEO build output —
// update this list by hand if a new tool is added to the registry.
const TOOL_IDS = new Set([
  "merge", "split", "rotate", "deletepages", "extractpages", "organize",
  "crop", "watermark", "pagenumbers", "protect", "compress", "edit",
  "pdf2word", "word2pdf", "pdf2jpg", "jpg2pdf", "pdf2excel", "excel2pdf",
  "mergeexcel", "sign", "reorder", "addblank", "headerfooter", "invertpdf",
  "flatten", "fillform", "imgcompress", "imgresize", "imgcrop", "imgconvert",
  "imgwatermark", "imginvert", "unlock", "repair", "pdf2pptx",
]);

const RATE_LIMIT_PER_HOUR = 30; // per hashed-IP, generous for a real visitor rating several tools
const VOTER_TOKEN_MAX_LEN = 128;

function store() {
  return getStore({ name: "ratings", consistency: "strong" });
}

function json(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store" },
  });
}

// A pepper only widens the hash search space for the anonymous voter
// token/IP before they're used as storage keys — it is not protecting a
// credential or secret payload, so a documented, override-able default is
// honest (no real secret is "hardcoded") rather than a security hole.
// Set RATING_HASH_PEPPER in Netlify's environment variables for
// production; see README/this file's own header comment.
const PEPPER = process.env.RATING_HASH_PEPPER || "yoyopdf-ratings-default-pepper-v1";

function hash(value) {
  return crypto.createHash("sha256").update(PEPPER + ":" + value).digest("hex");
}

function isValidRating(value) {
  return Number.isInteger(value) && value >= 1 && value <= 5;
}

function emptyAggregate() {
  const now = new Date().toISOString();
  return { voteCount: 0, ratingSum: 0, createdAt: now, updatedAt: now };
}

function toPublic(aggregate, extra) {
  const voteCount = aggregate?.voteCount || 0;
  const ratingSum = aggregate?.ratingSum || 0;
  return {
    voteCount,
    average: voteCount > 0 ? Math.round((ratingSum / voteCount) * 100) / 100 : null,
    ...extra,
  };
}

/**
 * Read-modify-write against one Blobs key. `consistency:"strong"` on the
 * store makes the read see the most recent write, but this is NOT a
 * compare-and-swap — two requests landing in the same instant can still
 * both read the same starting value and one write can clobber the other's
 * increment. For a five-star click counter the practical exposure is
 * small (worst case: one lost vote out of a burst of truly simultaneous
 * submissions), and it is disclosed here and in the final report rather
 * than silently assumed away.
 */
async function readModifyWrite(key, mutate) {
  const s = store();
  const current = (await s.get(key, { type: "json" })) || emptyAggregate();
  const next = mutate(current);
  next.updatedAt = new Date().toISOString();
  await s.setJSON(key, next);
  return next;
}

async function checkRateLimit(request, context) {
  const ip = context.ip || request.headers.get("x-nf-client-connection-ip") || "unknown";
  const bucket = new Date().toISOString().slice(0, 13); // UTC hour bucket, e.g. 2026-01-01T09
  const key = `ratelimit/${hash(ip)}/${bucket}`;
  const s = store();
  const count = (await s.get(key, { type: "json" })) || 0;
  if (count >= RATE_LIMIT_PER_HOUR) return false;
  await s.setJSON(key, count + 1);
  return true;
}

/**
 * One vote per (voterToken, subject) pair, ever — a second submission from
 * the same anonymous token UPDATES that voter's own prior rating (adjusts
 * ratingSum, leaves voteCount unchanged) instead of being rejected or
 * silently counted again, which is both the friendlier UX (changing your
 * mind about a rating) and the actual anti-inflation mechanism: voteCount
 * can only ever grow by one per distinct voter token. This is
 * server-authoritative — the client never sends a vote count, only a
 * rating value and its own anonymous token.
 */
async function applyVote(aggregateKey, voterKey, ratingValue) {
  const s = store();
  const priorVote = await s.get(voterKey, { type: "json" });
  const aggregate = await readModifyWrite(aggregateKey, (current) => {
    if (priorVote) {
      return { ...current, ratingSum: current.ratingSum - priorVote.rating + ratingValue };
    }
    return { ...current, voteCount: current.voteCount + 1, ratingSum: current.ratingSum + ratingValue };
  });
  await s.setJSON(voterKey, { rating: ratingValue, votedAt: new Date().toISOString() });
  return { aggregate, wasUpdate: Boolean(priorVote) };
}

async function handleGet(url) {
  const type = url.searchParams.get("type");
  const s = store();

  if (type === "tool") {
    const id = url.searchParams.get("id") || "";
    if (!TOOL_IDS.has(id)) return json({ error: "unknown tool id" }, 400);
    const aggregate = await s.get(`tool/${id}`, { type: "json" });
    return json({ toolId: id, ...toPublic(aggregate) });
  }

  if (type === "site") {
    const aggregate = await s.get("site", { type: "json" });
    return json(toPublic(aggregate));
  }

  if (type === "all") {
    const [overall, site] = await Promise.all([
      s.get("overall", { type: "json" }),
      s.get("site", { type: "json" }),
    ]);
    return json({ overallToolRating: toPublic(overall), siteRating: toPublic(site) });
  }

  return json({ error: "type must be one of: tool, site, all" }, 400);
}

async function handlePost(request, context) {
  let body;
  try {
    body = await request.json();
  } catch {
    return json({ error: "malformed request body" }, 400);
  }

  const { type, id, rating, voterToken } = body || {};
  if (type !== "tool" && type !== "site") return json({ error: "type must be 'tool' or 'site'" }, 400);
  if (!isValidRating(rating)) return json({ error: "rating must be an integer from 1 to 5" }, 400);
  if (typeof voterToken !== "string" || !voterToken || voterToken.length > VOTER_TOKEN_MAX_LEN) {
    return json({ error: "missing or invalid voterToken" }, 400);
  }
  if (type === "tool" && !TOOL_IDS.has(id)) return json({ error: "unknown tool id" }, 400);

  const withinLimit = await checkRateLimit(request, context);
  if (!withinLimit) return json({ error: "too many rating submissions — please try again later" }, 429);

  const hashedVoter = hash(voterToken);

  if (type === "site") {
    const { aggregate, wasUpdate } = await applyVote("site", `voter/site/${hashedVoter}`, rating);
    return json({ ...toPublic(aggregate), wasUpdate });
  }

  // Tool vote: update the tool's own aggregate AND the sitewide
  // vote-weighted "overall tool rating" aggregate together, so the
  // homepage's single `type=all` read never has to re-sum every tool.
  const { aggregate: toolAggregate, wasUpdate } = await applyVote(
    `tool/${id}`,
    `voter/tool/${id}/${hashedVoter}`,
    rating
  );
  // The "overall" aggregate tracks the same voter (by id-scoped voter key
  // above) implicitly: if this voter already rated this tool, adjust the
  // overall sum by the same delta instead of double-counting.
  const overallVoterKey = `voter/overall/${id}/${hashedVoter}`;
  const priorOverallVote = await store().get(overallVoterKey, { type: "json" });
  const overallAggregate = await readModifyWrite("overall", (current) => {
    if (priorOverallVote) {
      return { ...current, ratingSum: current.ratingSum - priorOverallVote.rating + rating };
    }
    return { ...current, voteCount: current.voteCount + 1, ratingSum: current.ratingSum + rating };
  });
  await store().setJSON(overallVoterKey, { rating, votedAt: new Date().toISOString() });

  return json({ toolId: id, ...toPublic(toolAggregate), wasUpdate, overallToolRating: toPublic(overallAggregate) });
}

export default async (request, context) => {
  const url = new URL(request.url);
  if (request.method === "GET") return handleGet(url);
  if (request.method === "POST") return handlePost(request, context);
  return json({ error: "method not allowed" }, 405);
};
